# Site settings
title: YoQ Blog
SEOTitle: YongQiang 的博客 | YongQiang Blog
header-img: img/home-bg.jpg
email: byq0502@gmail.com
description: "这里是 @Yongqiang 的个人博客，与你一起发现更大的世界 | 要做一个有 swag 的程序员"
keyword: "YongQiang, 勇强, 幻想师, @yongqiang1995, YongQ Blog, 博客, 个人网站, 互联网, Web, JavaScript, 深度学习, LLM, 数学"
url: "https://yongqiang.me" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: yongqiang1995
zhihu_username: yongqiang1995
github_username: yongqiang1995
twitter_username: yongqiang1995
#facebook_username:  yongqiang1995
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# plugins:
  # - jekyll-paginate
  # - jekyll-gist
  # - jemoji

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: https-yongqiang1995-github-io

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: yongqiang.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "资深炼丹员, 深度学习专家 😁😁 <br> React Team @ OPENAI"
sidebar-avatar: https://github.com/yongqiang1995.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false  # is true: app ready for offline use

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "虚位以待", href: "https://github.com/yongqiang1995"}, 
    { title: "Baidu", href: "http://www.baidu.com/" },
    { title: "Google", href: "https://www.google.com/" },
  ]
